-- Crear base de datos si no existe.
CREATE DATABASE IF NOT EXISTS INGSWI_WOODCHESS;

-- Crear usuario si no existe.
CREATE USER IF NOT EXISTS 'user_woodchess'@'localhost' IDENTIFIED BY 'Woodchess123#$';

-- Dar permisos al usuario sobre la base de datos.
GRANT ALL PRIVILEGES ON INGSWI_WOODCHESS.* TO 'user_woodchess'@'localhost';

-- Aplicar cambios.
FLUSH PRIVILEGES;

-- Usar base de datos.
USE INGSWI_WOODCHESS;

CREATE TABLE USUARIO (
    USU_RUT INT PRIMARY KEY NOT NULL,
    USU_NOMBRE VARCHAR(50) NOT NULL,
    USU_APELLIDO VARCHAR(50) NOT NULL,
    USU_EMAIL VARCHAR(50) NOT NULL UNIQUE,
    USU_CONTRA VARCHAR(255) NOT NULL,
    USU_ROL VARCHAR(3) NOT NULL,
    USU_TELEF VARCHAR(9) NOT NULL UNIQUE
);

CREATE TABLE PRODUCTO (
    PROD_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROD_NOMBRE VARCHAR(50) NOT NULL,
    PROD_DESC VARCHAR(255),
    PROD_STOCK INT NOT NULL,
    PROD_PRECIO INT NOT NULL
);

CREATE TABLE PEDIDO (
    PED_ID INT AUTO_INCREMENT PRIMARY KEY,
    PED_USURUT INT NOT NULL,
    PED_ESTADO VARCHAR(20) NOT NULL,
    PED_CALLE VARCHAR(50),
    PED_NUMERO VARCHAR(10),
    PED_COMUNA VARCHAR(50),
    PED_REGION VARCHAR(50),
    PED_INDEXTRA VARCHAR(100),
    PED_PTOTAL INT NOT NULL,
    PED_TOKEN VARCHAR(255),
    PED_FCREADO DATETIME NOT NULL,
    PED_FACTUAL DATETIME NOT NULL,
    CONSTRAINT fk_pedido_usuario FOREIGN KEY (PED_USURUT) REFERENCES USUARIO(USU_RUT)
);

CREATE TABLE MATERIAL (
    MAT_ID INT AUTO_INCREMENT PRIMARY KEY,
    MAT_NOMBRE VARCHAR(50) NOT NULL,
    MAT_DESC VARCHAR(255),
    MAT_IMAGEN VARCHAR(50) NOT NULL,
    MAT_DISP INT(1) NOT NULL DEFAULT 1,
    MAT_RDIFFUSE VARCHAR(50) NOT NULL,
    MAT_RNORMAL VARCHAR(50) NOT NULL,
    MAT_RROUGH VARCHAR(50) NOT NULL
);

CREATE TABLE PEDIDO_PRODUCTO (
    PEPR_ID INT AUTO_INCREMENT PRIMARY KEY,
    PEPR_PEDID INT NOT NULL,
    PEPR_PRODID INT NOT NULL,
    PEPR_MATPRI INT,
    PEPR_MATSEC INT,
    PEPR_MATTER INT,
    PEPR_MATCUAT INT,
    CONSTRAINT fk_pepr_pedido FOREIGN KEY (PEPR_PEDID) REFERENCES PEDIDO(PED_ID),
    CONSTRAINT fk_pepr_producto FOREIGN KEY (PEPR_PRODID) REFERENCES PRODUCTO(PROD_ID),
    CONSTRAINT fk_pepr_matpri FOREIGN KEY (PEPR_MATPRI) REFERENCES MATERIAL(MAT_ID),
    CONSTRAINT fk_pepr_matsec FOREIGN KEY (PEPR_MATSEC) REFERENCES MATERIAL(MAT_ID),
    CONSTRAINT fk_pepr_matter FOREIGN KEY (PEPR_MATTER) REFERENCES MATERIAL(MAT_ID),
    CONSTRAINT fk_pepr_matcuat FOREIGN KEY (PEPR_MATCUAT) REFERENCES MATERIAL(MAT_ID)
);

CREATE TABLE COMENTARIO (
    COM_ID INT AUTO_INCREMENT PRIMARY KEY,
    COM_PRODID INT NOT NULL,
    COM_USURUT INT NOT NULL,
    COM_CALIF INT(1) NOT NULL,
    COM_TITULO VARCHAR(50) NOT NULL,
    COM_DESC VARCHAR(255),
    COM_FECHA DATETIME NOT NULL,
    CONSTRAINT fk_com_producto FOREIGN KEY (COM_PRODID) REFERENCES PRODUCTO(PROD_ID),
    CONSTRAINT fk_com_usuario FOREIGN KEY (COM_USURUT) REFERENCES USUARIO(USU_RUT)
);

CREATE TABLE FOTOGRAFIA (
    FOTO_ID INT AUTO_INCREMENT PRIMARY KEY,
    FOTO_COMID INT NOT NULL,
    FOTO_RUTA VARCHAR(255) NOT NULL,
    CONSTRAINT fk_foto_comentario FOREIGN KEY (FOTO_COMID) REFERENCES COMENTARIO(COM_ID)
);

CREATE TABLE IMAGEN (
    IMA_ID INT AUTO_INCREMENT PRIMARY KEY,
    IMA_PRODID INT NOT NULL,
    IMA_RUTA VARCHAR(50) NOT NULL,
    IMA_PRINCIPAL INT(1) NOT NULL DEFAULT 0,
    CONSTRAINT fk_ima_producto FOREIGN KEY (IMA_PRODID) REFERENCES PRODUCTO(PROD_ID)
);

CREATE TABLE CARRO (
    CAR_ID INT AUTO_INCREMENT PRIMARY KEY,
    CAR_USURUT INT NOT NULL,
    CAR_PRODID INT NOT NULL,
    CAR_MAT1 INT,
    CAR_MAT2 INT,
    CAR_MAT3 INT,
    CAR_MAT4 INT,
    CONSTRAINT fk_car_usuario FOREIGN KEY (CAR_USURUT) REFERENCES USUARIO(USU_RUT),
    CONSTRAINT fk_car_producto FOREIGN KEY (CAR_PRODID) REFERENCES PRODUCTO(PROD_ID),
    CONSTRAINT fk_car_material1 FOREIGN KEY (CAR_MAT1) REFERENCES MATERIAL(MAT_ID),
    CONSTRAINT fk_car_material2 FOREIGN KEY (CAR_MAT2) REFERENCES MATERIAL(MAT_ID),
    CONSTRAINT fk_car_material3 FOREIGN KEY (CAR_MAT3) REFERENCES MATERIAL(MAT_ID),
    CONSTRAINT fk_car_material4 FOREIGN KEY (CAR_MAT4) REFERENCES MATERIAL(MAT_ID)
);